# Generated by Django 5.0.4 on 2024-04-12 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Samples', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleddirectors',
            name='pin',
            field=models.CharField(max_length=20, verbose_name='pin'),
        ),
    ]
