# Generated by Django 5.0.3 on 2024-03-07 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='abstractmodel',
            unique_together={('row_id', 'psp_id', 'gender', 'reporting_date')},
        ),
        migrations.RemoveField(
            model_name='mobileinformation',
            name='mobile_psp_info',
        ),
        migrations.RemoveField(
            model_name='scheduleddirectors',
            name='complaints',
        ),
        migrations.AddField(
            model_name='mobileinformation',
            name='psp_customer_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='samples.abstractmodel'),
        ),
        migrations.AddField(
            model_name='scheduleddirectors',
            name='psp_customer_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='samples.abstractmodel'),
        ),
        migrations.AlterField(
            model_name='abstractmodel',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('C', 'Coporate'), ('O', 'Other')], max_length=5, verbose_name='gender'),
        ),
        migrations.AlterField(
            model_name='customercomplaints',
            name='psp_customer_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='samples.abstractmodel'),
        ),
        migrations.RemoveField(
            model_name='abstractmodel',
            name='complaints',
        ),
    ]
