# Generated by Django 5.0.2 on 2024-02-29 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0002_alter_customercomplaints_reporting_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abstractmodel',
            name='reporting_date',
            field=models.DateField(verbose_name='reporting_date'),
        ),
    ]
