# Generated by Django 5.0.4 on 2024-04-15 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Samples', '0002_alter_scheduleddirectors_pin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduleddirectors',
            name='psp_customer_info_id',
        ),
    ]
