# Generated by Django 5.0.3 on 2024-03-15 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0003_alter_scheduleddirectors_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobileinformation',
            name='mobile_psp_info',
            field=models.CharField(max_length=255, null=True, verbose_name='mobile_psp_info'),
        ),
    ]
