# Generated by Django 5.0.2 on 2024-02-29 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0003_alter_abstractmodel_reporting_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abstractmodel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
