# Generated by Django 5.0.3 on 2024-03-15 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0004_mobileinformation_mobile_psp_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mobileinformation',
            name='mobile_psp_info',
        ),
    ]
