# Generated by Django 5.0.2 on 2024-02-29 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0004_alter_abstractmodel_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abstractmodel',
            name='psp_customer_info',
        ),
        migrations.AddField(
            model_name='customercomplaints',
            name='psp_customer_info',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='samples.abstractmodel'),
        ),
        migrations.AddField(
            model_name='mobileinformation',
            name='mobile_psp_info',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='samples.abstractmodel'),
        ),
    ]
