# Generated by Django 5.0.2 on 2024-02-29 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0005_remove_abstractmodel_psp_customer_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobileinformation',
            name='agent_cash_deposits',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='agent_cash_deposits'),
        ),
        migrations.AlterField(
            model_name='mobileinformation',
            name='agent_cash_deposits_bank',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='agent_cash_deposits_bank'),
        ),
        migrations.AlterField(
            model_name='mobileinformation',
            name='agent_cash_withdrawal_bank',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='agent_cash_withdrawal_bank'),
        ),
        migrations.AlterField(
            model_name='mobileinformation',
            name='cash_in_volume',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='cash_volume'),
        ),
        migrations.AlterField(
            model_name='mobileinformation',
            name='cash_out_volume',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='cash_out_volume'),
        ),
        migrations.AlterField(
            model_name='mobileinformation',
            name='float_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='float_amount'),
        ),
        migrations.AlterField(
            model_name='mobileinformation',
            name='value_agent_cash_withdrawal_bank',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='value_agent_cash_withdrawal_bank'),
        ),
        migrations.AlterField(
            model_name='mobileinformation',
            name='value_cash_in',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='value_cash_in'),
        ),
        migrations.AlterField(
            model_name='mobileinformation',
            name='value_cash_out',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='value_cash_out'),
        ),
    ]
