# Generated by Django 5.0.2 on 2024-02-28 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0011_alter_abstractmodel_reporting_date_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='customercomplaints',
            unique_together=set(),
        ),
    ]
