# Generated by Django 5.0.2 on 2024-02-28 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0013_alter_scheduleddirectors_pin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleddirectors',
            name='pin',
            field=models.CharField(max_length=20, verbose_name='pin'),
        ),
    ]
