# Generated by Django 5.0.2 on 2024-02-28 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0014_alter_scheduleddirectors_pin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mobileinformation',
            name='complaints',
        ),
    ]
